### ISSUE TITLE
2.3.X Checklist

### ISSUE THREAD

**Issue by Bartz24** [Bartz24/SkyResources#94]
2.3 might take a while after 2.3.0

- [ ] Add an automatic cutter
- [ ] Fix all 2.3 issues here
- [ ] Add fancy ItemHandlerHelper code to other places. also clean up code
- [x] removing the advancedRecipes config
- [x] new alchemical glass -> crystal shard recipe
- [x] buffing gem drops
